### ISSUE TITLE
Shader Model entry for Kepler in Feature Table is inaccurate

### ISSUE THREAD

**Issue by PrismaticFlower** [Devaniti/D3d12infoGUI#10]
Hey, so unless I'm missing something (which is always possible) on the final driver available for Kepler GPUs the Shader Model caps out at 6.5 and on the [Feature Table](https://d3d12infodb.boolka.dev/FeatureTable.html) it's listed at 6.6. I'm guessing the reports for it were generated with experimental shader models turned on? Kepler GPUs' Resource Binding caps out at Tier 2 so they can't strictly be said to be SM 6.6 capable, even if the driver reports support in experimental mode. 

Given the architecture's age it's far from the biggest issue but for the sake of accuracy I thought I would just raise it and you can do what you want with it.

Also it probably won't be useful but here is the output from d3d12info I am basing this on. (Which unless I'm mistaken is with the final driver for the GPU.) [GTX 770 d3d12info output.txt](https://github.com/user-attachments/files/17944517/GTX.770.d3d12info.output.txt) I don't have ready access to the GPU but I booted up with it and grabbed this a while a go for my own reference. I'm happy to sort out submitting a report from it another day for the sake of posterity, if that'd be useful.

**Comment by Devaniti** [comment]
Sorry for not replying for a week, totally missed this issue
In older versions of D3d12info, all of the experimental features were always enabled and so reports states support for SM 6.6
We've seen it as an issue and in latest D3d12info/GUI this is no longer the case (see https://github.com/sawickiap/D3d12info/pull/19)
As soon as we get new report for Kepler from latest build of D3d12infoGUI with same or newer driver, this will get resolved as that report will get used instead
I'll keep it open for the time being, as a reminder that it is a problem
If you have access to that hardware please consider submitting a report with latest driver/GUI
And when someone does, I'll close this issue

**Comment by PrismaticFlower** [comment]
That's all good. I've submitted a report from it just now.

**Comment by Devaniti** [comment]
Nice, thanks
It's now reporting properly in the table
