### ISSUE TITLE
[Feature Request] Support for D3D12_FEATURE_DATA_FORMAT_SUPPORT

### ISSUE THREAD

**Issue by kylawl** [Devaniti/D3d12infoGUI#12]
When working some of the more exotic formats, the gpu support can be quite mixed for UAVs. If you're working on console ports especially, it's really handy to have the exhaustive list of formats and which D3D12_FORMAT_SUPPORT2 flags they've got.

This db is incredibly valuable info, thanks for the great work!

/ Kyle

**Comment by Devaniti** [comment]
Yeah, that's one of the few next things planned
Will note that we should also include SUPPORT2 as well

**Comment by Devaniti** [comment]
Resolved with #13 and release in https://github.com/Devaniti/D3d12infoGUI/releases/tag/v1.6.0
Can see the table for new reports e.g. https://d3d12infodb.boolka.dev/ID.html?ID=401
